services:
  orders-db:
    container_name: orders_database
    image: postgres:16.2
    volumes:
      - postgres-orders-microservice:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb
volumes:
  postgres-orders-microservice:
